language: go

go:
  - 1.8
  - 1.8.1
  - 1.8.2
  - 1.8.3
  - 1.9
  - 1.9.1
  - 1.9.2
  - 1.9.3
  - 1.9.4
  - tip

sudo: false

go_import_path: github.com/novln/lemon

before_install:
  - go get -u github.com/mattn/goveralls
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install

script:
  - scripts/test
  - scripts/lint

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
