language: go

go:
  - "1.10"
  - "1.10.1"
  - "1.10.2"
  - "1.10.3"
  - "1.10.4"
  - "1.11"
  - "1.11.1"
  - "tip"

sudo: false

go_import_path: github.com/novln/lemon

script:
  - scripts/test
  - scripts/lint
  - scripts/coverage --analyze

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
