language: go

go:
  - 1.7
  - 1.7.1
  - 1.7.2
  - 1.7.3
  - tip

sudo: false

go_import_path: github.com/november-eleven/lemon

before_install:
  - go get -u github.com/mattn/goveralls

install:
  - go get -u github.com/alecthomas/gometalinter

script:
  - go test -race .
  - gometalinter --vendor -j1 --disable=gotype --disable=dupl --enable=lll --enable=gofmt --deadline=120s --line-length=120 --tests .
  - go test -covermode=count -coverprofile .

after_success:
  - goveralls -coverprofile=coverage.out -service=travis-ci

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
